version: "3.0"

services:
  db:
    image: postgres
    container_name: post
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mysecretpassword
    restart: always

  api:
    image: fastapi_image
    network_mode: host
    command: uvicorn main:app --host 0.0.0.0 --port 80
    container_name: api
    ports:
      - 80:80
    restart: always
    depends_on:
      - db

  front:
    image: react_image
    command: npm start
    container_name: front
    ports:
      - 3000:3000
    restart: always
    depends_on:
      - api

# docker-compose up -d --build